USE sakila;

-- Challenge - Joining on multiple tables
-- Write SQL queries to perform the following tasks using the Sakila database:

-- 1.List the number of films per category.
SELECT c.name as name_category , count(f.film_id) as nro_films
FROM film f
LEFT JOIN film_category fc ON f.film_id = fc.film_id
LEFT JOIN category c ON c.category_id = fc.category_id
GROUP BY name_category;

-- 2.Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city,co.country
FROM store s
LEFT JOIN address a ON s.address_id = a.address_id
LEFT JOIN city c ON c.city_id = a.city_id
LEFT JOIN country co ON co.country_id = c.country_id;

-- 3.Calculate the total revenue generated by each store in dollars.
SELECT s.store_id as stores, sum(py.amount) as amount_dollars
FROM store s
LEFT JOIN staff sf ON s.store_id = sf.store_id
LEFT JOIN payment py ON py.staff_id = sf.staff_id
GROUP BY stores;


-- 4.Determine the average running time of films for each category.
SELECT ct.name category_name, avg(f.length) as runnig_time_avg
FROM film f
LEFT JOIN film_category fc ON f.film_id = fc.film_id
LEFT JOIN category ct ON ct.category_id = fc.category_id
GROUP BY category_name;